version: '3.9'

services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - PAYMENT_SERVICE_URL=http://payment-service:4000
      - TRANSACTION_SERVICE_URL=http://transaction-service:4100
    networks:
      - shared-infra

networks:
  shared-infra:
    external: true
